default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  # For some reason Rails creates test DB with Dev ENV, so have to explicitly set the name:
  database: alive_test

production:
  <<: *default
